/* 
-- Transaction POS Header Table
select * from [GOLF_WAREHOUSE].[dbo].[PS_DOC_HDR]

-- Transaction POS Line Item Table
select * from [GOLF_WAREHOUSE].[dbo].[PS_DOC_LIN]

-- STORE Master File
select * from [GOLF_WAREHOUSE].[dbo].[PS_STR]

-- STATION Master File
select * from [GOLF_WAREHOUSE].[dbo].[PS_STA]

-- LOCATION Master File
select * from [GOLF_WAREHOUSE].[dbo].[IM_LOC]

-- PRICE Master File *You can omit this because the price info is already in the line item
select * from [GOLF_WAREHOUSE].[dbo].[IM_PRC]

-- ITEM CATEGORY Master File
select * from [GOLF_WAREHOUSE].[dbo].[IM_CATEG_COD]

-- ITEM CATEGORY Master File *You can omit this because the description info is already in the line item
select * from [GOLF_WAREHOUSE].[dbo].[IM_ITEM]

select a.STK_LOC_ID, b.LOC_ID from [GOLF_WAREHOUSE].[dbo].[PS_DOC_LIN] a
LEFT OUTER JOIN [GOLF_WAREHOUSE].[dbo].[IM_LOC] b ON a.STK_LOC_ID = b.LOC_ID


-- TRANSACTION QUERY
USE GOLF_WAREHOUSE

SELECT dbo.PS_DOC_LIN.DOC_ID, dbo.PS_DOC_LIN.STR_ID, dbo.PS_STR.DESCR AS STORE, dbo.PS_DOC_LIN.LIN_SEQ_NO, dbo.PS_DOC_HDR.DOC_TYP, dbo.PS_DOC_HDR.CUST_NO, dbo.PS_DOC_LIN.STA_ID, dbo.PS_STA.DESCR AS STATION, dbo.PS_DOC_HDR.DRW_ID, 
             dbo.PS_DRW.DESCR AS DRAWER, dbo.PS_DOC_LIN.TKT_NO, dbo.PS_DOC_LIN.LIN_TYP, dbo.PS_DOC_LIN.PRC, dbo.PS_DOC_LIN.ITEM_NO, dbo.PS_DOC_LIN.DESCR, dbo.PS_DOC_LIN.RETAIL_VAL, dbo.PS_DOC_LIN.CALC_PRC, dbo.PS_DOC_LIN.EXT_COST, 
             dbo.PS_DOC_LIN.STK_LOC_ID, dbo.IM_LOC.DESCR AS LOCATION, dbo.PS_DOC_LIN.REG_PRC, dbo.PS_DOC_LIN.PRC_LOC_ID, dbo.PS_DOC_LIN.CATEG_COD, dbo.IM_CATEG_COD.DESCR AS CATEGORY, dbo.PS_DOC_LIN.SUBCAT_COD, 
             dbo.IM_SUBCAT_COD.DESCR AS SUBCAT, dbo.PS_DOC_LIN.ITEM_VEND_NO, dbo.PS_DOC_LIN.QTY_SOLD, dbo.PS_DOC_LIN.QTY_NUMER, dbo.PS_DOC_LIN.QTY_DENOM, dbo.PS_DOC_LIN.QTY_UNIT, dbo.PS_DOC_LIN.SELL_UNIT, dbo.PS_DOC_LIN.RET_REAS, 
             dbo.PS_DOC_LIN.IS_TXBL, dbo.PS_DOC_LIN.SLS_REP, dbo.PS_DOC_LIN.REF, dbo.PS_DOC_LIN.ITEM_TYP, dbo.PS_DOC_LIN.PRC_1, dbo.PS_DOC_LIN.QTY_DECS, dbo.PS_DOC_LIN.PRC_DECS, dbo.PS_DOC_LIN.BARCOD, dbo.PS_DOC_LIN.TAX_CATEG, 
             dbo.PS_DOC_LIN.TRK_METH, dbo.PS_DOC_LIN.UNIT_WEIGHT, dbo.PS_DOC_LIN.UNIT_CUBE, dbo.PS_DOC_LIN.LIN_GUID, dbo.PS_DOC_LIN.DIM_1_UPR, dbo.PS_DOC_LIN.DIM_2_UPR, dbo.PS_DOC_LIN.DIM_3_UPR, dbo.PS_DOC_LIN.UNIT_COST, dbo.PS_DOC_LIN.SER_NO, 
             dbo.PS_DOC_LIN.QTY_RET, dbo.PS_DOC_LIN.GROSS_EXT_PRC, dbo.PS_DOC_LIN.DISP_EXT_PRC, dbo.PS_DOC_LIN.HAS_PRC_OVRD, dbo.PS_DOC_LIN.PRC_OVRD_REAS, dbo.PS_DOC_LIN.COST_OF_SLS_PCT, dbo.PS_DOC_LIN.MIX_MATCH_COD, 
             dbo.PS_DOC_LIN.USR_ENTD_PRC, dbo.PS_DOC_LIN.GROSS_DISP_EXT_PRC, dbo.PS_DOC_LIN.IS_DISCNTBL, dbo.PS_DOC_LIN.CALC_EXT_PRC, dbo.PS_DOC_LIN.IS_WEIGHED, dbo.PS_DOC_LIN.TAX_AMT_ALLOC, dbo.PS_DOC_LIN.NORM_TAX_AMT_ALLOC
FROM   dbo.PS_DOC_HDR INNER JOIN
             dbo.PS_DOC_LIN ON dbo.PS_DOC_HDR.DOC_ID = dbo.PS_DOC_LIN.DOC_ID INNER JOIN
             dbo.PS_STR ON dbo.PS_DOC_HDR.STR_ID = dbo.PS_STR.STR_ID INNER JOIN
             dbo.PS_STA ON dbo.PS_DOC_HDR.STR_ID = dbo.PS_STA.STR_ID AND dbo.PS_DOC_HDR.STA_ID = dbo.PS_STA.STA_ID AND dbo.PS_STR.STR_ID = dbo.PS_STA.STR_ID INNER JOIN
             dbo.PS_DRW ON dbo.PS_STR.STR_ID = dbo.PS_DRW.STR_ID INNER JOIN
             dbo.IM_CATEG_COD ON dbo.PS_DOC_LIN.CATEG_COD = dbo.IM_CATEG_COD.CATEG_COD INNER JOIN
             dbo.IM_SUBCAT_COD ON dbo.PS_DOC_LIN.SUBCAT_COD = dbo.IM_SUBCAT_COD.SUBCAT_COD LEFT OUTER JOIN
             dbo.IM_LOC ON dbo.PS_DOC_LIN.STK_LOC_ID = dbo.IM_LOC.LOC_ID

*/
